version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../:/var/www/html
    environment:
      # Variables de entorno para la conexión a la DB
      DB_HOST: db
      DB_DATABASE: newlifedb
      DB_USERNAME: user
      DB_PASSWORD: userpassword
    networks:
      - appnet

  nginx:
    image: openresty/openresty:alpine
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: newlifedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ../scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet:

volumes:
  dbdata:
